---
# file: roles/openstack-full/tasks/main.yml

# Debian has a kernel upgrade from 3.14 to 3.16
# So we need to restart the compute nodes and migrate the instances before.
- name: migrate instances
  script: migrate.sh {{ ansible_fqdn }} {{ os_username }} {{ os_tenant_name }} {{ os_password }} {{ os_auth_url }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# RabbitMQ is upgraded in RHEL7
- name: stop rabbitmq
  service: name=rabbitmq-server state=stopped
  tags: before_config
  when: ansible_distribution == 'RedHat

# MySQL is upgraded in RHEL7
# since we don't know if the node is master or not, we stop mysql anyway
- name: stop mysql
  service: name={{ item }} state=stopped
  with_items:
    - mysqld
    - mysql-boostrap
  tags: before_config
  ignore_errors: yes
  when: ansible_distribution == 'RedHat'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: reload systemd scripts list
  command: systemctl daemon-reload
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: start rabbitmq
  service: name=rabbitmq-server state=started
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['openstack-full'][-1]

# Red Hat upgrade Galera to 25.3.5-5.el7ost
# since we start in serial mode one by one, we are sure here that the first node
# in the list will be master.
# For other nodes, they will be started by Puppet later.
- name: create systemd mysql-bootstrap script
  copy: src=mysql-bootstrap.service dest=/usr/lib/systemd/system/mysql-bootstrap.service
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['openstack-full'][-1]

- name: bootstrap mysql cluster again
  service: name=mysql-bootstrap state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat' and inventory_hostname == groups['openstack-full'][-1]

# libvirtd is updated on RHEL7
- name: restart libvirtd after upgrade
  service: name=libvirtd state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: restart nova-compute after upgrade
  service: name=openstack-nova-compute state=restarted
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: allow instance scheduling on the compute node
  command: nova-manage service enable --service nova-compute --host {{ ansible_hostname }}
  tags: before_config
  when: ansible_distribution == 'Debian'

# after upgrade, heat-api is zombie
- name: kill heat-api process
  command: pkill -9 heat-api
  tags: before_config
  when: ansible_distribution == 'Debian'

# then, restart it
- name: start heat-api service
  service: name=heat-api state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

# HAproxy has been updated in Debian
# from 1.5~dev26-2~bpo70+1 to 1.5.4-1~bpo70+2
- name: restart HAproxy service
  service: name=haproxy state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

# Red Hat OSP5 upgrades Icehouse to 2014.1.3
# from 2014.1.2-2.el7ost to 2014.1.3-1.el7ost
- name: restart services after upgrade
  service: name={{ item }} state=restarted
  with_items:
    - httpd
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-metadata-agent
    - neutron-metering-agent
    - neutron-metering-agent
    - neutron-openvswitch-agent
    - neutron-openvswitch-agent
    - neutron-server
    - openstack-ceilometer-alarm-evaluator
    - openstack-ceilometer-alarm-notifier
    - openstack-ceilometer-api
    - openstack-ceilometer-collector
    - openstack-ceilometer-compute
    - openstack-ceilometer-notification
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
    - openstack-glance-api
    - openstack-glance-registry
    - openstack-heat-api
    - openstack-heat-api-cfn
    - openstack-heat-api-cloudwatch
    - openstack-heat-engine
    - openstack-keystone
    - openstack-nova-api
    - openstack-nova-cert
    - openstack-nova-compute
    - openstack-nova-conductor
    - openstack-nova-consoleauth
    - openstack-nova-scheduler
    - openstack-nova-spicehtml5proxy
    - openstack-swift-account
    - openstack-swift-container
    - openstack-swift-object
    - openstack-swift-proxy
  tags: before_config
  when: ansible_distribution == 'RedHat'

- name: update keystone database
  command: keystone-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'

- name: update nova database
  command: nova-manage db sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'

- name: update glance database
  command: glance-manage db_sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'

- name: update cinder database
  command: cinder-manage db sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'

- name: update neutron database
  command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'

- name: update heat database
  command: heat-manage --config-file /etc/heat/heat.conf db_sync
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'


- name: restart ceilometer-agent-central managed by pacemaker
  command: pcs resource cleanup ceilometer-agent-central
  tags: before_config
  when: inventory_hostname == groups['openstack-full'][-1] and ansible_distribution == 'RedHat'

# sensu has been upgrade in Debian
# from 0.14.0-1 to 0.16.0-1
- name: restart sensu
  service: name=sensu-client state=restarted
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: restart neutron-plugin-openvswitch-agent after upgrade
  service: name=neutron-plugin-openvswitch-agent state=restarted
  tags: after_config
  when: ansible_distribution == 'Debian'

- name: restart neutron-l3-agent after upgrade
  service: name=neutron-l3-agent state=restarted
  tags: after_config

- name: restart apache after upgrade
  service: name=httpd state=restarted
  tags: after_config
  when: ansible_distribution == 'RedHat'
