---
# file: roles/load-balancer/tasks/main.yml

- seboolean: name=rsync_client state=yes persistent=yes
  tags: before_config
  when: ansible_distribution == 'RedHat'

# Dirty hack to upgade /usr/sbin/edeploy before actual upgrade
# and benefit of rsync with attributes feature.
# Useful when running SElinux before J.1.0.0
- name: upgrade edeploy script
  copy: src=edeploy dest=/usr/sbin/edeploy mode=0755
  tags: before_config

- name: stop HAproxy service
  service: name=haproxy state=stopped
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: edeploy upgrade
  edeploy: command=upgrade version={{ distro }}-{{ version }}
  tags: before_config

- name: reboot the servers
  command: /sbin/reboot -t now
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: Wait for server to come up
  local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started
  tags: before_config
  when: ansible_distribution == 'Debian'

- name: Ensure old puppet ssl files are removed
  file: path=/var/lib/puppet/ssl state=absent
  tags: before_config

- name: change mysqlchk port from 9200 to 8200
  replace:
    dest={{ item }}
    regexp='9200'
    replace='8200'
  with_items:
    - "/etc/services"
    - "/etc/xinetd.d/mysqlchk"
    - "/etc/haproxy/haproxy.cfg"
  tags: before_config

- name: restart xinetd
  service: name=xinetd state=restarted
  tags: before_config

- name: start HAproxy service
  service: name=haproxy state=restarted
  tags: before_config
